### ISSUE TITLE
Syncfusion.ThriftHive.Base.dll

### ISSUE THREAD

**Issue by Mrsevic** [syncfusion/spark-sql-with-dashboard#1]
Syncfusion.ThriftHive.Base is not referenced or available anywhere on internet.

**Comment by rajendransp** [comment]
You can find the Syncfusion.ThriftHive.Base assembly as part of Big Data Platform builds.
https://www.syncfusion.com/products/big-data 

once installed, you can find the assembly in below location.
 <LocalDrive>:\Syncfusion\BigData\<version>\BigDataSDK\Syncfusion Helper Assemblies\<frameworkversion>
